export const mockLeagueData = {
  teams: [
    {
      name: "TEAM_MAHOMES",
      rank: 1,
      record: "9-2",
      totalValue: 1247.5,
      roster: [
        {
          name: "Patrick Mahomes",
          position: "QB",
          team: "KC",
          value: 28.5,
          weeklyTrend: 2.1,
          projectedPoints: 24.8,
          weeklyProjectionTrend: 1.3,
        },
        {
          name: "Christian McCaffrey",
          position: "RB",
          team: "SF",
          value: 52.1,
          weeklyTrend: 0.5,
          projectedPoints: 22.3,
          weeklyProjectionTrend: -0.8,
        },
        {
          name: "Austin Ekeler",
          position: "RB",
          team: "LAC",
          value: 45.3,
          weeklyTrend: -1.2,
          projectedPoints: 18.7,
          weeklyProjectionTrend: 2.1,
        },
        {
          name: "Stefon Diggs",
          position: "WR",
          team: "BUF",
          value: 42.1,
          weeklyTrend: 0.4,
          projectedPoints: 17.2,
          weeklyProjectionTrend: -1.1,
        },
        {
          name: "Mike Evans",
          position: "WR",
          team: "TB",
          value: 38.9,
          weeklyTrend: 1.8,
          projectedPoints: 16.4,
          weeklyProjectionTrend: 0.7,
        },
        {
          name: "Travis Kelce",
          position: "TE",
          team: "KC",
          value: 32.1,
          weeklyTrend: 0.1,
          projectedPoints: 14.6,
          weeklyProjectionTrend: 0.3,
        },
        {
          name: "Justin Tucker",
          position: "K",
          team: "BAL",
          value: 9.8,
          weeklyTrend: 0.2,
          projectedPoints: 8.9,
          weeklyProjectionTrend: 0.1,
        },
        {
          name: "San Francisco 49ers",
          position: "DST",
          team: "SF",
          value: 14.2,
          weeklyTrend: 2.3,
          projectedPoints: 10.1,
          weeklyProjectionTrend: 1.8,
        },
      ],
    },
    {
      name: "TEAM_ALLEN",
      rank: 2,
      record: "8-3",
      totalValue: 1189.25,
      roster: [
        {
          name: "Josh Allen",
          position: "QB",
          team: "BUF",
          value: 27.8,
          weeklyTrend: 1.5,
          projectedPoints: 24.2,
          weeklyProjectionTrend: 0.9,
        },
        {
          name: "Derrick Henry",
          position: "RB",
          team: "TEN",
          value: 42.8,
          weeklyTrend: 2.3,
          projectedPoints: 19.8,
          weeklyProjectionTrend: 1.7,
        },
        {
          name: "Saquon Barkley",
          position: "RB",
          team: "NYG",
          value: 41.2,
          weeklyTrend: -0.8,
          projectedPoints: 18.3,
          weeklyProjectionTrend: -0.4,
        },
        {
          name: "Justin Jefferson",
          position: "WR",
          team: "MIN",
          value: 48.9,
          weeklyTrend: 0.2,
          projectedPoints: 19.4,
          weeklyProjectionTrend: 0.5,
        },
        {
          name: "Cooper Kupp",
          position: "WR",
          team: "LAR",
          value: 46.7,
          weeklyTrend: -1.1,
          projectedPoints: 18.9,
          weeklyProjectionTrend: -0.6,
        },
        {
          name: "Mark Andrews",
          position: "TE",
          team: "BAL",
          value: 29.4,
          weeklyTrend: 0.7,
          projectedPoints: 13.2,
          weeklyProjectionTrend: 0.4,
        },
        {
          name: "Daniel Carlson",
          position: "K",
          team: "LV",
          value: 8.9,
          weeklyTrend: -0.1,
          projectedPoints: 8.4,
          weeklyProjectionTrend: 0.0,
        },
        {
          name: "Buffalo Bills",
          position: "DST",
          team: "BUF",
          value: 13.1,
          weeklyTrend: 1.4,
          projectedPoints: 9.7,
          weeklyProjectionTrend: 1.1,
        },
      ],
    },
    {
      name: "TEAM_BURROW",
      rank: 3,
      record: "7-4",
      totalValue: 1156.75,
      roster: [
        {
          name: "Joe Burrow",
          position: "QB",
          team: "CIN",
          value: 26.3,
          weeklyTrend: 0.8,
          projectedPoints: 23.1,
          weeklyProjectionTrend: 0.6,
        },
        {
          name: "Nick Chubb",
          position: "RB",
          team: "CLE",
          value: 39.7,
          weeklyTrend: -2.1,
          projectedPoints: 17.9,
          weeklyProjectionTrend: -1.3,
        },
        {
          name: "Alvin Kamara",
          position: "RB",
          team: "NO",
          value: 38.4,
          weeklyTrend: 1.6,
          projectedPoints: 17.2,
          weeklyProjectionTrend: 1.2,
        },
        {
          name: "Davante Adams",
          position: "WR",
          team: "LV",
          value: 44.8,
          weeklyTrend: -0.3,
          projectedPoints: 18.6,
          weeklyProjectionTrend: -0.1,
        },
        {
          name: "Keenan Allen",
          position: "WR",
          team: "LAC",
          value: 37.2,
          weeklyTrend: 0.9,
          projectedPoints: 15.8,
          weeklyProjectionTrend: 0.7,
        },
        {
          name: "George Kittle",
          position: "TE",
          team: "SF",
          value: 28.7,
          weeklyTrend: 1.2,
          projectedPoints: 12.9,
          weeklyProjectionTrend: 0.8,
        },
        {
          name: "Harrison Butker",
          position: "K",
          team: "KC",
          value: 9.2,
          weeklyTrend: 0.3,
          projectedPoints: 8.7,
          weeklyProjectionTrend: 0.2,
        },
        {
          name: "Dallas Cowboys",
          position: "DST",
          team: "DAL",
          value: 12.8,
          weeklyTrend: 0.6,
          projectedPoints: 9.3,
          weeklyProjectionTrend: 0.4,
        },
      ],
    },
    {
      name: "TEAM_JACKSON",
      rank: 4,
      record: "7-4",
      totalValue: 1134.5,
      roster: [
        {
          name: "Lamar Jackson",
          position: "QB",
          team: "BAL",
          value: 27.8,
          weeklyTrend: 1.5,
          projectedPoints: 24.2,
          weeklyProjectionTrend: 1.1,
        },
        {
          name: "Jonathan Taylor",
          position: "RB",
          team: "IND",
          value: 40.1,
          weeklyTrend: 0.4,
          projectedPoints: 18.4,
          weeklyProjectionTrend: 0.3,
        },
        {
          name: "Dalvin Cook",
          position: "RB",
          team: "MIN",
          value: 37.9,
          weeklyTrend: -1.7,
          projectedPoints: 16.8,
          weeklyProjectionTrend: -1.2,
        },
        {
          name: "Tyreek Hill",
          position: "WR",
          team: "MIA",
          value: 47.3,
          weeklyTrend: 0.7,
          projectedPoints: 19.1,
          weeklyProjectionTrend: 0.5,
        },
        {
          name: "A.J. Brown",
          position: "WR",
          team: "PHI",
          value: 41.6,
          weeklyTrend: 1.3,
          projectedPoints: 17.4,
          weeklyProjectionTrend: 0.9,
        },
        {
          name: "T.J. Hockenson",
          position: "TE",
          team: "MIN",
          value: 26.8,
          weeklyTrend: -0.5,
          projectedPoints: 11.7,
          weeklyProjectionTrend: -0.3,
        },
        {
          name: "Tyler Bass",
          position: "K",
          team: "BUF",
          value: 8.2,
          weeklyTrend: -0.3,
          projectedPoints: 8.1,
          weeklyProjectionTrend: -0.2,
        },
        {
          name: "Miami Dolphins",
          position: "DST",
          team: "MIA",
          value: 12.1,
          weeklyTrend: 1.8,
          projectedPoints: 9.4,
          weeklyProjectionTrend: 1.4,
        },
      ],
    },
    {
      name: "TEAM_HERBERT",
      rank: 5,
      record: "6-5",
      totalValue: 1098.25,
      roster: [
        {
          name: "Justin Herbert",
          position: "QB",
          team: "LAC",
          value: 25.7,
          weeklyTrend: 0.6,
          projectedPoints: 22.8,
          weeklyProjectionTrend: 0.4,
        },
        {
          name: "Aaron Jones",
          position: "RB",
          team: "GB",
          value: 36.2,
          weeklyTrend: 1.1,
          projectedPoints: 16.3,
          weeklyProjectionTrend: 0.8,
        },
        {
          name: "Joe Mixon",
          position: "RB",
          team: "CIN",
          value: 35.8,
          weeklyTrend: -0.9,
          projectedPoints: 15.9,
          weeklyProjectionTrend: -0.6,
        },
        {
          name: "DeAndre Hopkins",
          position: "WR",
          team: "ARI",
          value: 39.4,
          weeklyTrend: 0.2,
          projectedPoints: 16.7,
          weeklyProjectionTrend: 0.1,
        },
        {
          name: "DK Metcalf",
          position: "WR",
          team: "SEA",
          value: 36.1,
          weeklyTrend: 1.4,
          projectedPoints: 15.2,
          weeklyProjectionTrend: 1.0,
        },
        {
          name: "Kyle Pitts",
          position: "TE",
          team: "ATL",
          value: 25.3,
          weeklyTrend: -1.8,
          projectedPoints: 10.8,
          weeklyProjectionTrend: -1.2,
        },
        {
          name: "Matt Gay",
          position: "K",
          team: "LAR",
          value: 7.9,
          weeklyTrend: 0.1,
          projectedPoints: 7.8,
          weeklyProjectionTrend: 0.0,
        },
        {
          name: "New England Patriots",
          position: "DST",
          team: "NE",
          value: 11.4,
          weeklyTrend: 0.8,
          projectedPoints: 8.9,
          weeklyProjectionTrend: 0.6,
        },
      ],
    },
    {
      name: "TEAM_RODGERS",
      rank: 6,
      record: "6-5",
      totalValue: 1076.75,
      roster: [
        {
          name: "Aaron Rodgers",
          position: "QB",
          team: "GB",
          value: 24.9,
          weeklyTrend: -0.4,
          projectedPoints: 22.3,
          weeklyProjectionTrend: -0.3,
        },
        {
          name: "Leonard Fournette",
          position: "RB",
          team: "TB",
          value: 34.6,
          weeklyTrend: 0.7,
          projectedPoints: 15.4,
          weeklyProjectionTrend: 0.5,
        },
        {
          name: "Ezekiel Elliott",
          position: "RB",
          team: "DAL",
          value: 33.2,
          weeklyTrend: -1.3,
          projectedPoints: 14.8,
          weeklyProjectionTrend: -0.9,
        },
        {
          name: "CeeDee Lamb",
          position: "WR",
          team: "DAL",
          value: 43.7,
          weeklyTrend: 0.9,
          projectedPoints: 18.2,
          weeklyProjectionTrend: 0.6,
        },
        {
          name: "Amari Cooper",
          position: "WR",
          team: "CLE",
          value: 34.8,
          weeklyTrend: -0.6,
          projectedPoints: 14.6,
          weeklyProjectionTrend: -0.4,
        },
        {
          name: "Dallas Goedert",
          position: "TE",
          team: "PHI",
          value: 24.1,
          weeklyTrend: 1.5,
          projectedPoints: 10.3,
          weeklyProjectionTrend: 1.1,
        },
        {
          name: "Younghoe Koo",
          position: "K",
          team: "ATL",
          value: 8.7,
          weeklyTrend: 0.4,
          projectedPoints: 8.3,
          weeklyProjectionTrend: 0.3,
        },
        {
          name: "Pittsburgh Steelers",
          position: "DST",
          team: "PIT",
          value: 11.9,
          weeklyTrend: 1.2,
          projectedPoints: 9.1,
          weeklyProjectionTrend: 0.9,
        },
      ],
    },
  ],
}
